"""S4-R2 fixed TRAIN-only observation-standardization contract tests."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
import torch
from gymnasium import spaces

from quadrotor_diffusion_ppo.ppo.contract import PPO_CONFIG, REWARD_CONTRACT_HASH
from quadrotor_diffusion_ppo.ppo.normalization import (
    CONSTANT_FEATURE_SCALE,
    STD_FLOOR,
    FixedObservationStandardizer,
    derive_train_statistics,
)


ROOT = Path(__file__).resolve().parents[1]
TRAIN_NPZ = ROOT / "artifacts" / "s2" / "dataset" / "train.npz"


def test_statistics_are_exactly_s2_train_observations_only():
    statistics = derive_train_statistics(TRAIN_NPZ)
    with np.load(TRAIN_NPZ, allow_pickle=False) as data:
        observations = data["observations"].astype(np.float64)
    assert statistics.sample_count == 129_458
    assert statistics.mean.shape == statistics.scale.shape == (34,)
    assert np.array_equal(statistics.mean, observations.mean(axis=0, dtype=np.float64))
    assert np.array_equal(statistics.raw_std, observations.std(axis=0, dtype=np.float64))
    assert statistics.source_sha256 == "701a1d36b767ff41347b1dac60868922ce5033ee8db27721daf891613125db21"
    assert len(statistics.contract_sha256) == 64


def test_constant_feature_uses_safe_unit_scale_without_amplification():
    statistics = derive_train_statistics(TRAIN_NPZ)
    assert np.flatnonzero(statistics.constant_mask).tolist() == [20]
    assert statistics.raw_std[20] < STD_FLOOR
    assert statistics.scale[20] == CONSTANT_FEATURE_SCALE == 1.0
    assert statistics.scale.min() > 0.0


def test_standardizer_is_34d_finite_fixed_and_non_updating():
    statistics = derive_train_statistics(TRAIN_NPZ)
    extractor = FixedObservationStandardizer(
        spaces.Box(-np.inf, np.inf, shape=(34,), dtype=np.float32),
        statistics.mean.tolist(), statistics.scale.tolist(),
    )
    before = {name: value.clone() for name, value in extractor.state_dict().items()}
    batch = torch.as_tensor(np.vstack((statistics.mean, statistics.mean + statistics.scale)), dtype=torch.float32)
    output = extractor(batch)
    assert output.shape == (2, 34)
    assert torch.isfinite(output).all()
    assert torch.allclose(output[0], torch.zeros(34), atol=2e-5)
    assert torch.allclose(output[1], torch.ones(34), atol=2e-5)
    extractor(batch * 2)
    assert all(torch.equal(value, extractor.state_dict()[name]) for name, value in before.items())


def test_standardizer_state_dict_round_trip_preserves_statistics():
    statistics = derive_train_statistics(TRAIN_NPZ)
    observation_space = spaces.Box(-np.inf, np.inf, shape=(34,), dtype=np.float32)
    first = FixedObservationStandardizer(observation_space, statistics.mean.tolist(), statistics.scale.tolist())
    second = FixedObservationStandardizer(observation_space, [0.0] * 34, [1.0] * 34)
    second.load_state_dict(first.state_dict())
    assert torch.equal(first.fixed_mean, second.fixed_mean)
    assert torch.equal(first.fixed_scale, second.fixed_scale)


def test_frozen_reward_and_ppo_algorithm_contract_unchanged():
    assert REWARD_CONTRACT_HASH == "92afefbf338d0ccbbcc42c12a572327413ca66f46bf1f061f637e68d125ae3ec"
    expected = {
        "total_env_steps": 500_000, "n_envs": 8, "learning_rate": 3e-4,
        "n_steps": 1024, "batch_size": 512, "n_epochs": 10, "gamma": 0.99,
        "gae_lambda": 0.95, "clip_range": 0.2, "ent_coef": 0.0,
        "vf_coef": 0.5, "max_grad_norm": 0.5,
    }
    assert {key: PPO_CONFIG[key] for key in expected} == expected


def test_r2_source_has_no_diffusion_teacher_or_premature_test_dataset_access():
    source = (ROOT / "scripts" / "run_s4r2_ppo.py").read_text(encoding="utf-8").lower()
    assert "quadrotor_diffusion_ppo.diffusion" not in source
    assert "quadrotor_diffusion_ppo.expert" not in source
    assert "model.learn(total_timesteps=total_env_steps" in source
    assert source.index("if val_gate:") < source.index("tasks[\"test\"]")
    assert "include_test=val_gate" in source


def test_normalization_contract_artifact_when_present():
    path = ROOT / "artifacts" / "s4r2" / "normalization.json"
    if not path.exists():
        pytest.skip("generated by R2 preflight")
    contract = json.loads(path.read_text(encoding="utf-8"))
    assert contract["source"].endswith("train.npz::observations")
    assert contract["constant_feature_indices"] == [20]
    assert contract["dimension"] == 34
